version: "3"

services:
    api:
        build: .
        container_name: api-boileplate-node-mysql
        command: npm run start
        depends_on:
            - mysqldb
        ports:
            - 8081:8081
        volumes:
            - .:/usr/src/app

    mysqldb:
        container_name: db-boilerplate-node-mysql
        env_file: ./.env
        environment:
            MYSQL_PASSWORD: ${DATABASE_PW}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PW}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_ID}
        expose:
            - 3306
        image: mysql:8.0
        ports:
            - 3306:3306
        restart: always
        volumes:
            - db-config:/etc/mysql
            - db-data:/var/lib/mysql
            - ./db/backup/files/:/data_backup/

volumes:
    db-config:
    db-data:
